id: P006877
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 12:28:09.293844
source_metadata:
  id: bdr:W21907
  title: ཁམས་ཉག་རོང་ཁ་བ་ལུང་རིའི་ཟངས་མདོག་དཔལ་རིའི་དཀར་ཆག
  author: ''
  volumes:
    b3b3b937546641f9922b1d08216a510f:
      image_group_id: I1GS105537
      title: ''
      volume_number: 1
      total_pages: 138
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
