id: I424E9455
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T06:56:16+00:00'
last_modified: '2022-06-08T07:30:52.417244+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21907
  title: ཁམས་ཉག་རོང་ཁ་བ་ལུང་རིའི་ཟངས་མདོག་དཔལ་རིའི་དཀར་ཆག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B57E:
      image_group_id: I1GS105537
      title: ''
      total_pages: 138
      order: 1
      base_file: B57E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
